{"errorMessage": "Could not find a suitable TLS CA certificate bundle, invalid path: /opt/python/certifi/cacert.pem", "errorType": "OSError", "requestId": "102ab7b5-ce31-466c-87f1-369aff37ca50", "stackTrace": ["  File \"/var/task/scraper_lambda.py\", line 25, in lambda_handler\n    response = requests.get(TARGET_URL, timeout=10)\n", "  File \"/opt/python/requests/api.py\", line 73, in get\n    return request(\"get\", url, params=params, **kwargs)\n", "  File \"/opt/python/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n", "  File \"/opt/python/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n", "  File \"/opt/python/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n", "  File \"/opt/python/requests/adapters.py\", line 616, in send\n    self.cert_verify(conn, request.url, verify, cert)\n", "  File \"/opt/python/requests/adapters.py\", line 303, in cert_verify\n    raise OSError(\n"]}